"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-26 17:25:59.366497
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signing_keys',
    sa.Column('kid', sa.String(length=40), nullable=False),
    sa.Column('public_key_pem', sa.Text(), nullable=False),
    sa.Column('private_key_pem', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('kid')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('flagged', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('accounts',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('labels',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('subject', sa.String(length=80), nullable=False),
    sa.Column('label', sa.String(length=40), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('labeled_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['labeled_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scans',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('viewer_user_id', sa.String(length=64), nullable=True),
    sa.Column('tx', sa.String(length=40), nullable=True),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('verdict', sa.String(length=12), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['viewer_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scans_tx'), 'scans', ['tx'], unique=False)
    op.create_table('transfers',
    sa.Column('tx', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('refund_of', sa.String(length=40), nullable=True),
    sa.Column('payer_account_id', sa.String(length=40), nullable=False),
    sa.Column('payee_account_id', sa.String(length=40), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('refunded_minor', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_band', sa.String(length=8), nullable=False),
    sa.Column('risk_reasons', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reversed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['payee_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['payer_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['refund_of'], ['transfers.tx'], ),
    sa.PrimaryKeyConstraint('tx')
    )
    op.create_index(op.f('ix_transfers_payee_account_id'), 'transfers', ['payee_account_id'], unique=False)
    op.create_index(op.f('ix_transfers_payer_account_id'), 'transfers', ['payer_account_id'], unique=False)
    op.create_table('cases',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('transfer_tx', sa.String(length=40), nullable=True),
    sa.Column('scan_id', sa.String(length=40), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('resolution', sa.String(length=300), nullable=True),
    sa.Column('dedupe_key', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.ForeignKeyConstraint(['transfer_tx'], ['transfers.tx'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_dedupe_key'), 'cases', ['dedupe_key'], unique=False)
    op.create_table('confirmations',
    sa.Column('tx', sa.String(length=40), nullable=False),
    sa.Column('confirmed_by', sa.String(length=64), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tx'], ['transfers.tx'], ),
    sa.PrimaryKeyConstraint('tx')
    )
    op.create_table('idempotency_keys',
    sa.Column('scope_key', sa.String(length=200), nullable=False),
    sa.Column('tx', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tx'], ['transfers.tx'], ),
    sa.PrimaryKeyConstraint('scope_key')
    )
    op.create_table('journal_entries',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('transfer_tx', sa.String(length=40), nullable=True),
    sa.Column('memo', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['transfer_tx'], ['transfers.tx'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_entries_created_at'), 'journal_entries', ['created_at'], unique=False)
    op.create_index(op.f('ix_journal_entries_transfer_tx'), 'journal_entries', ['transfer_tx'], unique=False)
    op.create_table('receipts',
    sa.Column('tx', sa.String(length=40), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('kid', sa.String(length=40), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['kid'], ['signing_keys.kid'], ),
    sa.ForeignKeyConstraint(['tx'], ['transfers.tx'], ),
    sa.PrimaryKeyConstraint('tx')
    )
    op.create_table('ledger_lines',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('journal_id', sa.String(length=40), nullable=False),
    sa.Column('account_id', sa.String(length=40), nullable=False),
    sa.Column('direction', sa.String(length=2), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['journal_id'], ['journal_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ledger_lines_account', 'ledger_lines', ['account_id'], unique=False)
    op.create_index(op.f('ix_ledger_lines_journal_id'), 'ledger_lines', ['journal_id'], unique=False)
    # ### end Alembic commands ###

    # The ledger is append-only (§3.7): reject UPDATE and DELETE at the database level.
    # Corrections are new journal entries. (TRUNCATE, used only by the sandbox reset, is allowed.)
    op.execute("""
        CREATE FUNCTION ledger_append_only() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            RAISE EXCEPTION 'ledger tables are append-only (% on %)', TG_OP, TG_TABLE_NAME;
        END;
        $$;
    """)
    for table in ("journal_entries", "ledger_lines"):
        op.execute(f"""
            CREATE TRIGGER {table}_append_only BEFORE UPDATE OR DELETE ON {table}
            FOR EACH ROW EXECUTE FUNCTION ledger_append_only();
        """)


def downgrade() -> None:
    for table in ("journal_entries", "ledger_lines"):
        op.execute(f"DROP TRIGGER IF EXISTS {table}_append_only ON {table}")
    op.execute("DROP FUNCTION IF EXISTS ledger_append_only()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ledger_lines_journal_id'), table_name='ledger_lines')
    op.drop_index('ix_ledger_lines_account', table_name='ledger_lines')
    op.drop_table('ledger_lines')
    op.drop_table('receipts')
    op.drop_index(op.f('ix_journal_entries_transfer_tx'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_created_at'), table_name='journal_entries')
    op.drop_table('journal_entries')
    op.drop_table('idempotency_keys')
    op.drop_table('confirmations')
    op.drop_index(op.f('ix_cases_dedupe_key'), table_name='cases')
    op.drop_table('cases')
    op.drop_index(op.f('ix_transfers_payer_account_id'), table_name='transfers')
    op.drop_index(op.f('ix_transfers_payee_account_id'), table_name='transfers')
    op.drop_table('transfers')
    op.drop_index(op.f('ix_scans_tx'), table_name='scans')
    op.drop_table('scans')
    op.drop_table('labels')
    op.drop_table('accounts')
    op.drop_table('users')
    op.drop_table('signing_keys')
    # ### end Alembic commands ###
